;;;; ***********************************************************************
;;;; FILE IDENTIFICATION
;;;;
;;;; Name:          functions.lisp
;;;; Project:       folio - the Bard runtime
;;;; Purpose:       series functions
;;;; Author:        mikel evins
;;;; Copyright:     2013 by mikel evins
;;;;
;;;; ***********************************************************************

(in-package :net.bardcode.folio.series)

;;;add-first
;;;any
;;;by
;;;catenate 
;;;choose 
;;;choose-if 
;;;chunk
;;;coalesce
;;;collect 
;;;collect-alist 
;;;collect-and 
;;;collect-append
;;;collect-file 
;;;collect-first 
;;;collect-fn 
;;;collect-hash 
;;;collect-ignore
;;;collect-last 
;;;collect-length 
;;;collect-max 
;;;collect-min
;;;collect-nconc 
;;;collect-nth
;;;collect-or 
;;;collect-plist
;;;collect-product 
;;;collect-stream
;;;collect-sum 
;;;collecting-fn 
;;;cotruncate 
;;;drop
;;;drop-while
;;;element
;;;empty?
;;;expand 
;;;fgather-next 
;;;fgather-result 
;;;fgathering
;;;fgatherlet 
;;;filter
;;;first
;;;gather-next 
;;;gather-result 
;;;gatherer  
;;;gathering
;;;gatherlet 
;;;generator 
;;;head
;;;image 
;;;indefinite-extent
;;;indexes 
;;;interleave 
;;;interpose
;;;iterate 
;;;latch 
;;;make 
;;;make-series 
;;;map-fn 
;;;mapping
;;;mask 
;;;mingle
;;;next-in 
;;;next-out
;;;off-line-port
;;;optimizable-series-function
;;;partition 
;;;positions
;;;prefix-match?
;;;previous 
;;;producing 
;;;propagate-alterability
;;;range 
;;;range-from
;;;remove
;;;remove-if
;;;remove-if-not
;;;repeat
;;;rest 
;;;result-of 
;;;scan
;;;scan 
;;;scan-alist
;;;scan-file 
;;;scan-fn 
;;;scan-fn-inclusive 
;;;scan-hash 
;;;scan-lists-of-lists
;;;scan-lists-of-lists-fringe 
;;;scan-multiple 
;;;scan-plist 
;;;scan-range
;;;scan-stream 
;;;scan-sublists 
;;;scan-symbols 
;;;second 
;;;select 
;;;sequence 
;;;sequence? 
;;;series
;;;series 
;;;series-element-type  
;;;series?
;;;split 
;;;split-if 
;;;spread 
;;;subseries 
;;;substitute 
;;;substitute-if 
;;;substitute-if-not 
;;;tail 
;;;tails 
;;;take
;;;take-by 
;;;take-while
;;;terminate-producing
;;;to-alter 
;;;until 
;;;until-if 
;;;unzip 
;;;wb-seq 
;;;wb-seq?
;;;zip
